### ISSUE TITLE
Bump minimum API version

### ISSUE THREAD

**Issue by antonlukin** [stevebest/passport-vkontakte#52] opened 2020-06-15 09:00 UTC
According new [API Version Life Cycle](https://vk.com/dev/constant_version_updates) we should bump minimum API version to prevent current error:

```json
{"success":false,"message":"Invalid request: versions below 5.21 are deprecated. Version param should be passed as \"v\". \"version\" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates"}
```

**Comment by AndrewTkachenko** [comment] 2020-06-17 09:16
@antonlukin for fix it in production use `apiVersion` option for set valid vk api version. 
Note: Valid version is 5.89, not 5.21 like in error response from API

**Comment by antonlukin** [comment] 2020-06-17 09:56
@AndrewTkachenko I know about it, but suggest to add minimum required api version by default

**Comment by stevebest** [comment] 2020-06-18 03:42
Anyone willing to submit a PR?

**Comment by antonlukin** [comment] 2020-06-18 07:47
I'll do it soon

**Comment by stevebest** [comment] 2020-06-22 04:03
Merged #53 and published as 0.3.3

Could you please confirm it is working as intended? (I have deleted my own VK account long time ago and have no intention to start a new one, even for testing.)

Thanks!

**Comment by antonlukin** [comment] 2020-06-22 07:40
Looks working. Thanks!

**Closed** 2020-06-22 07:43 UTC
